### ISSUE TITLE
Add "SCIM sweep now" button in UI

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1067]
Services can already trigger a SCIM sweep using the API call `/api/scim/v2/sweep` but they can't easily trigger a SCIM sweep from the UI.  Please add a button for that on the SCIM server screen in the Service Details.

This can be used to test the SCIM server's handling of a sweep, but also to test the connection in general.

After execution a message should be displayed that the connection was successful or not.
For example:

![Image](https://user-images.githubusercontent.com/1842889/277625431-2ac351ab-3472-4366-bdee-cfa209bf63d7.png)

**Comment by FlorisFokkinga** [comment]
Suggestion to add a "Test Connection" button so that the entered credentials can be verified by the Service Administrator. The request to execute can be for example:
GET <url>/ServiceProviderConfig

This should normally result in a 200 OK (in combination with SCIM Server capabilities)

After execution a message should be displayed that the connection was successful or not.
For example



![Image](https://user-images.githubusercontent.com/1842889/277625431-2ac351ab-3472-4366-bdee-cfa209bf63d7.png)

If connection is not successful this could indicate:
* Url and/or token is not valid
* Firewall preventing incoming connections
* ServiceProviderConfig endpoint is not supported (we could alternatively use GET <url>/Users and <url>/Groups. These have to be supported is all cases.

**Comment by oharsta** [comment]
@FlorisFokkinga How do you think we can improve this? Show a popup if there are unsaved changes in the SCIM configuration?

**Comment by FlorisFokkinga** [comment]
How about combining the buttons into one 'Update & test' button?
