### ISSUE TITLE
SCIM can be enabled by service admins

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1239]
evaluate status of SCIM api.

**Comment by HarryKodden** [comment]
<google-sheets-html-origin><style type="text/css"></style>
LDAP | SCIM |  
-- | -- | --
flat.Groups | Groups |  
flat.People | Users |  
  |   |  
LDAP People | SCIM User |  
cn | urn:mace:surf.nl:sram:scim:extension:User.eduPersonUniqueId |  
sn | name.familyName |  
sshPublicKey [n] | x509Certificates[].value |  
uid | userName |  
displayName | displayName |  
eduPersonScopedAffiliation | urn:mace:surf.nl:sram:scim:extension:User.eduPersonScopedAffiliation |  
eduPersonUniqueId | urn:mace:surf.nl:sram:scim:extension:User.eduPersonUniqueId |  
givenName | name.givenName |  
mail [n] Effectively 1 ? | emais [] { primary: true, value: mail-address } |  
voPersonExternalAffiliation [n] | urn:mace:surf.nl:sram:scim:extension:User.voPersonExternalAffiliation !!! Just 1 |  
voPersonExternalID | urn:mace:surf.nl:sram:scim:extension:User.voPersonExternalId |  
voPersonStatus | n/a |  
  |   |  
LDAP Group | SCIM Group |  
entityID (part of DN) | n/a |  
cn | urn:mace:surf.nl:sram:scim:extension:Group.urn |  
description | urn:mace:surf.nl:sram:scim:extension:Group.description |  
businessCategory [n] | urn:mace:surf.nl:sram:scim:extension:Group.labels[] |  
displayName | displayName |  
labeledURI [n] | n/a |  
mail [n] | n/a |  
member [n] | member |  
organizationalStatus | n/a |  
uniqueIdentifier | externalId (identical to id when using SCIM Client) |  
  |   |  
LDAP Member | SCIM Member |  
dn [n] | $ref (complete SCIM address of User) |  
  | SCIM displayName of User |  
  | value (SCIM id of User |

**Comment by HarryKodden** [comment]
During conversation with developers of SURF ResearhCloud, it turned out that only 1 missing attribute in the SCIM interface compared to the LDAP contents, is blocking for them to migratie from LDAP to SCIM integration with SRAM.
That missing attribute is the current 'labeledURI' list. This attribute contains references to:
* URL of accepted user policy of the Service
* URL of the privacy policy of the Service
* URL of the LOGO of the Service
* URL of the LOGO of the Collaboration
* URL of the LOGO of the Organisation
* URL of the Collaboration in SRAM

I would suggest to add 'links[]' attribute to the existing 'urn:mace:surf.nl:sram:scim:extension:Group' extension.
Each link is a json object, like:
```
{
  "name": "<name>",
  "value": "<url>"
}
```

example: (SRAM SCIM Group Object)

```
  ...
  "urn:mace:surf.nl:sram:scim:extension:Group": {
  "description": "Artifical Intelligence computing",
  "labels": [
     "label_01"
  ],
  "urn": "ucc:collab01",
  "links": [
      {
        "name": "Accepted User Policy",
        "value": "https://..."
      },
      {
        "name": "Privacy Policy",
        "value": "https://..."
      },
      {
        "name": "Logo",
        "value": "https://..."
      },
      {
        "name": "SBS",
        "value": "https://sram.surf.nl/..."
      }
  ]
 }
 ...
```

**Comment by HarryKodden** [comment]
Created PR
https://github.com/SURFscz/SBS/pull/1518

During the development it turned out that details of ORGANISATION and SERVICE are not currently selected for SCIM.
For SCIM only following objects are selected:
- Collaborations
- Collaboration Groups/Members
- Services (connected to Collaboration) Groups/Members

Therefor the (only) links included are:
- Logo of the Collaboration
- Website-URL of the Collaboration

and not:
- Logo of Organisation (since Organisation object is not included at all in SCIM)
- Logo of Service (since Service object is not included in SCIM, only the Service Groups/Members)
- AUP / PP Since these are applicable to Service

**Comment by baszoetekouw** [comment]
works, see #1539
