### ISSUE TITLE
Call to `/api/users/me` takes 5 second

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1551]
This makes all of SRAM incredibly slow.
![Screenshot 2024-08-26 at 13 43 12](https://github.com/user-attachments/assets/879725b6-0fd2-4dff-bc73-90ddb3f39f94)

@oharsta do you have any suggestions how to debug this further?  Other people can't reproduce it, and I can't reproduce it on on test or acc, only on prod.

**Comment by oharsta** [comment]
The problem is the usage of `joinedload` for child collections. Rule of thumb is to use `selectinload` for collections and only use `joinedload` to load single element relationships. The cartesian product is exponential large with soo many joins and preliminary results with the migration to `joinedload` for child collections show substantial performance gains.

**Comment by oharsta** [comment]
@mrvanes The reset-code is mailed to the `{conf.mail_confsend_exceptions_recipients}` when the user is rate-limited. I have added the reset code functionality back to the rate-limited page. Furthermore an organisation admin can look up the user in the user tab of his / her organisation and also reset the TOTP.

**Comment by oharsta** [comment]
This is very hard to test on the test environment as a user is required to have memberships (organisation, service and collaboration). Agreed with Bas to test if everything works as it should and check the performance gains when this is deployed on production.
