### ISSUE TITLE
Enabling SCIM Push gives 'Embarrassment error...'

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#1649]
When you enable SCIM Push feature, You have to provide both Remote SCIM Server URL and the API token.
However, when you provide both, it will result in a 'Embarrassment error'

You can bypass this error by executing these steps:
* Enable SCIM Push
* Press update (!!!)
* Adjust scim token
* Press test to verify that the combination is valid 

Expected behaviour:
* Enable SCIM Push
* Adjust scim token
* Press update
* Press test

**Comment by oharsta** [comment]
Confirmed. The encryption / decryption functionality was added as an afterthought for SCIM service tokens, and especially the use of the remote SCIM endpoint in context used in the encryption / decryption of the token. The expected behaviour described above is definitely an improvement, however there are more scenario's where the functionality is broken. Especially in combination with "Test" functionality and "Change SCIM token".

This will require additional analysis and we also most likely need to hint to the user that there is no SCIM token yet, so one needs to be added. And the situation, that there is an existing SCIM token, and changing this in combination with the SCIM url is possible (which now leads to 400 responses)

**Comment by oharsta** [comment]
We also need to nullify all related SCIM attributes when SCIM is disabled in the  `update` implementation of `service.py`.

**Comment by oharsta** [comment]
Show warning dialog when trying to add / update the SCIM token when there is no valid SCIM URL

**Comment by HarryKodden** [comment]
Works !
