### ISSUE TITLE
Only show nudge indicator for open connection requests

### ISSUE THREAD

**Issue by logan-life** [SURFscz/SBS#1663]
The Connection requests tab displays a nudge indicator icon `!`. This type of icon is usually used to inform a user that something needs their attention. When there are open requests for the org admin to review and approve/ disapprove, it makes sense to display the icon. When there are no open requests to make a decision on, the icon should not be displayed.
![Image](https://github.com/user-attachments/assets/c7d952f5-6fe7-49b1-8e75-c851b165d75f)

**Comment by mrvanes** [comment]
The solution now _seems_ to be to completely remove the "Connection requests" tab once all requests have been approved or denied. That implies removing the nudge, but also removes the requests history fromm the org admin. Is that intended behaviour?

**Comment by oharsta** [comment]
@mrvanes It is a bit more complex. If an organisation is configured with "**Application connection request must be approved by the Organisation admin**" and an admin of a CO within that organisation requests a Service Connection, then the request appears in the _Connection Requests_ tab of the organisation. If the connection request is approved or denied by a ORG admin, then the settings of the service are checked. If the service allows for automatic connections, then the connection is made and the request remains visible in the _Connection Requests_ tab of the organisation. However when the service does not allow for  automatic connections, then the  service connection request is updated and `pending_organisation_approval` is set to `False`. The service connection request is no longer visible in the _Connection Requests_ tab of the organisation as the request now needs approval from the service administrator.  When there are no more service connection requests where `pending_organisation_approval` is `True` then the _Connection Requests_ tab is removed from the organisation detail page.

This is by design and nothing has changed in this implementation. The only change made in this story is the removal of the nudge indicator if there are no service connection requests with the status `open`. The logic to only display service connection requests where `pending_organisation_approval` is `True` was already in place.

**Comment by oharsta** [comment]
Screenshot of Approved and Denied service connection requests (with no Open requests, and therefore no nudge indicator) that allowed for an automatic connection based on the access rules of the Service

![Image](https://github.com/user-attachments/assets/c4f4e7bf-fa64-4bed-9f3f-4f32b6357948)

**Comment by mrvanes** [comment]
I have checked the explained behaviour and tested it to be completely as described.
