### ISSUE TITLE
As I user I want to be able to distinguish different users with one or more identical attributes

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#262]
Dus: zorg dat in alle tabellen waar een beperkte set gebruikersattributen getoond wordt, altijd ook de gebruikersnaam zichtbaar is.

Edit ArTe: dit raakt de wens om 'LoA op attributen' te tonen (iets wat (ook) nog niet uitgewerkt is)?

**Comment by baszoetekouw** [comment]
Staat op Edwins backlog

**Comment by baszoetekouw** [comment]
Op welke schermen is dit precies een probleem?

**Comment by FlorisFokkinga** [comment]
So, users can be shown ambiguously on many screens. If this is a problem on several screens, we should implement a general solution on every screen.

CO requests: 

![Image](https://user-images.githubusercontent.com/80269262/191772374-3cb479be-66fa-4ac2-9cdc-b00e11e379e6.png)

ORG admins:


![Image](https://user-images.githubusercontent.com/80269262/191772939-62847e77-6ed7-4571-bbe0-1965edeba86e.png)

CO admins:

![Image](https://user-images.githubusercontent.com/80269262/191773217-3ccbb6bd-90a7-4e6c-8ad8-a546c0adbd02.png)

CO members:

![Image](https://user-images.githubusercontent.com/80269262/191773264-3140d386-781f-4574-a9e5-f7f2215e1832.png)

CO groups:

![Image](https://user-images.githubusercontent.com/80269262/191773302-b5d2956b-5154-460a-89d8-63bb0a3abb08.png)

CO join requests:

![Image](https://user-images.githubusercontent.com/80269262/191773374-61d9724f-ee72-49b3-ba65-cfecc282bbfa.png)

Platform admins:

![Image](https://user-images.githubusercontent.com/80269262/191773491-0b107462-ec25-4dce-ab78-914840ab2276.png)

Service admins:

![Image](https://user-images.githubusercontent.com/80269262/191773548-47badd39-c1c6-449a-be01-d969d89ce4d8.png)

Service connection requests:

![Image](https://user-images.githubusercontent.com/80269262/191773651-f3e9a807-453e-4a02-8269-3926607fa469.png)

**Comment by arnoutt** [comment]
Overal waar user informatie wordt getoond moet ook de affiliatie (domein instelling) worden getoond (in SBS institution).

**Comment by FlorisFokkinga** [comment]
I think for humans the combination of email address and institution uniquely identifies a user. Since we already have a column where both full name and email address of the user is shown, adding a column with the institution solves this request.
Please always the institution column directly to the right of the name/email column.

- CO requests: add institution column directly to the right of 'requester' column
- CO join requests: move the institution column directly to the right of 'name/email' column
- Service connection requests: add institution column directly to the right of 'requester' column

**Comment by FlorisFokkinga** [comment]
The columns are there.

**Comment by baszoetekouw** [comment]
works as expected on acc.
