### ISSUE TITLE
Opening a Service screen can be very slow

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#273]
Sometimes a servcie screen (on prod) takes ~20 seconds to load.  See firefox screenshot:
![Screenshot 2022-08-18 at 19 31 32](https://user-images.githubusercontent.com/1461740/185458405-b0f243b1-61c2-47c3-8cc4-29df063a8ebc.png)

**Comment by oharsta** [comment]
@baszoetekouw  How many organisations are there in production? And how many collaborations are connected to this service? In the test environment it can took up to 3 seconds and that is because there are more than 1000 collaborations connected to the service. Possible solution is to lazily load the information on the other tabs and use pagination to have faster rendering.

**Comment by baszoetekouw** [comment]
On prod, there are 25 organisaties, 702 CO's.  There are only 2 collaborations connected, and the Service is anabled for all Organizations.

**Comment by baszoetekouw** [comment]
The weird thing is that it isn't always slow; when I tried a moment ago, the same page loaded very quickly.

**Comment by baszoetekouw** [comment]
I've checked the loadbalancer logs, and it seems the queiry s usually pretty fast (<200ms), and only occasionally it is slow:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/1461740/185629802-8901e97a-e4e6-41a9-b937-4417a9ac2163.png">

So I think I simply encountered some type of infra glitch yesterday.
