### ISSUE TITLE
Maak vooraf duidelijk welke velden verplicht zijn

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#318]
Als je een vers formulier invult, kun je vantevoren niet zien welke velden verplicht zijn.  Pas als je op submit/request/create duwt, worden vergeten velden rood. 

Kunnen we op de een of andere manier ook vooraf duidelijk maken welke velden je MOET invullen?

**Comment by arnoutt** [comment]
This is currently not part of the SURF Design System, as it seems. However, an error message should appear immediately after the focus changes, not only when the user presses submit. If that is not the case, we can fix that.

Otherwise I propose to postpone this issue to whenever we will start with aligning the design with the Design System.

**Comment by baszoetekouw** [comment]
Dit mist in het designsystem.  Bij Hanno neerleggen.

**Comment by FlorisFokkinga** [comment]
Requested a design: https://github.com/SURFnet/SURFDesignSystem/issues/1

**Comment by FlorisFokkinga** [comment]
This should be available in the design system. It's implemented in SBS itself for now.

**Comment by mrvanes** [comment]
I only see an * in form for a new collaboration, but that is also present in prd, so I don't see the change?
