### ISSUE TITLE
As a CO admin, I want my CO to remain active when a member logs into a connected service using PAM web login

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#346]

**Comment by oharsta** [comment]
Implemented the simple scenario: all Collaborations where the user is a member of and are directly linked to the PAM Service, are updated and get a new last_activity_date. There are corner-cases as a Service that is linked to the Organisation instead of the of Collaboration. These are not taken into account.

**Comment by FlorisFokkinga** [comment]
That should almost all relevant use cases. I will explain this in the documentation.

**Comment by baszoetekouw** [comment]
werkt op acc
