### ISSUE TITLE
Remove the step counter from the invitation landing page 

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#420]
# Current user flow #
<img width="1082" alt="image" src="https://github.com/SURFscz/SBS/assets/80269262/24be20a5-2bff-4a03-8a36-24355acfb20b">

<img width="707" alt="image" src="https://github.com/SURFscz/SBS/assets/80269262/addd55b3-f6d0-4da6-829e-083f54d42a03">

<img width="707" alt="image" src="https://github.com/SURFscz/SBS/assets/80269262/8816aedd-a8b4-4aa3-a936-16aaca78e7fc">

**Comment by FlorisFokkinga** [comment]
Consideration: because the user is yet unauthenticated, it is unknown if the users already has a SRAM profile. So it is also unknown how many steps the user will have to take after this to accept the invite. Also because the number of steps to authenticate with the IdP is completely unknown.
So I'm afraid we have to drop the 'Step 1 of #' circle.

**Comment by FlorisFokkinga** [comment]
Requested a split for roles in #433.

**Comment by mrvanes** [comment]
Correct
