### ISSUE TITLE
Display boolean selectors as radio buttons with question, check boxes for configuration

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#483]
Radio buttons force a deliberate choice if they have no default state.

## Good examples ##
This is an actual question for the admin, not a choice.

![Image](https://user-images.githubusercontent.com/80269262/192548229-bbc6794a-06ad-4833-9b32-2dd24133c3e7.png)

Here the admin can enable or disable the functionality at will. The label is a statement.

![Image](https://user-images.githubusercontent.com/80269262/192548367-355aab9a-af5e-4ff6-9d50-99539bbbb2ab.png)

## Bad example ##
This is not a question, but a configuration toggle.

![Image](https://user-images.githubusercontent.com/80269262/192547716-ec9688ab-1771-4dea-8383-42b2119e9ae5.png)

**Comment by baszoetekouw** [comment]
Floris maakt inventarisatie, daarna meenemen in designsystem.

**Comment by FlorisFokkinga** [comment]
## Organisations ##
<img width="434" alt="image" src="https://user-images.githubusercontent.com/80269262/214861955-fec81775-1f9e-4f7b-8311-b8d036130fe7.png">
Should both be checkboxes, unchecked by default. Remove the question mark

## Collaborations ##
<img width="376" alt="image" src="https://user-images.githubusercontent.com/80269262/214862386-578e74ab-30c1-408c-966f-37e124f7cef4.png">
Refrase to 'Allow join request' and 'Lidmaatschapsverzoeken toestaan' (remove the period).
Invert the setting (because the orginal phrasing was negative), checked by default.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/80269262/214862975-82cfd4db-f887-48a1-ae5e-b0e96995977d.png">
No changes

<img width="418" alt="image" src="https://user-images.githubusercontent.com/80269262/214863027-28560686-bd38-4db4-a4b2-3e7b74dbde43.png">
(Only shown while creating a CO, not while editing)
Refrase to 'Make me admin of this collaboration' and 'Maak mij beheerder van deze samenwerking'.

## Groups and service groups ##
<img width="359" alt="image" src="https://user-images.githubusercontent.com/80269262/214863631-a9532405-cca7-45c1-ab2f-77e160b4ddf3.png">
Remove the question mark.

## Services ##
<img width="427" alt="image" src="https://user-images.githubusercontent.com/80269262/214864817-174574a7-f32f-4b70-9a58-2d72ea596b6e.png">
Only remove the question mark.

<img width="194" alt="image" src="https://user-images.githubusercontent.com/80269262/214864877-d86a0f2a-060c-48e5-a682-27212fb1f52d.png">
Remove the default value, forcing the user to make a choice.

<img width="286" alt="image" src="https://user-images.githubusercontent.com/80269262/214865034-c213a3e1-2a0c-4dbd-b21d-894961004b1e.png">
<img width="192" alt="image" src="https://user-images.githubusercontent.com/80269262/214865082-8e1fa194-242d-4de3-b433-782b8211bcf3.png">
<img width="220" alt="image" src="https://user-images.githubusercontent.com/80269262/214865126-6895366d-ad8e-4bb0-9e1e-dc38eab76059.png">
<img width="189" alt="image" src="https://user-images.githubusercontent.com/80269262/214865157-a59540c4-1f5d-494f-9ee9-b9d7c4fae7e9.png">
<img width="406" alt="image" src="https://user-images.githubusercontent.com/80269262/214865209-d0c92c29-c522-4610-9fdf-eac69642cb24.png">
(SCIM only available on edit.)
Change all these to checkboxes, default value unchanged.
Remove 'enabled' and the question mark, so only the feature's name is displayed:

- Token-based introspection
- PAM web login
- SCIM provisioning
- SCIM Sweeping
- Delete orphan user and empty collaborations / groups

**Comment by baszoetekouw** [comment]
ede8f9b denk ik

**Comment by FlorisFokkinga** [comment]
Has been fixed.
