### ISSUE TITLE
Collaborations created in the API are not live updated in the websocket live stream

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#552]

**Comment by oharsta** [comment]
@baszoetekouw We don't currently emit websocket events when a CO is created. Which screen do you expect to update automatically? Only the ORG detail screen or also the CO overview of the platform admin?

**Comment by oharsta** [comment]
Do note that it now works, but we use a cookie to identify the session which each tab stores and refreshes in the local storage. Otherwise changes in one tab would not show up in another tab as the cookie is the same. But if you open a new tab with the flasgger API and POST a new CO, then the cookie from the other tab is send (because it is not refreshed) and changes are not picked up. To test this specific situation you'll need to use two browser.
