### ISSUE TITLE
Servicegroups improvements

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#562]
Hoge prio:
- if a CO has an existing group with the same name, service group is not created; I want the servicegroups to be always created.  Solution: allow duplicate groep names if the service is different.
- Bij de migratie wordt alleen de connectie gemaakt met bestaande groepen in de COs.  Servicegroepen die nog niet bestaan in de COs worden niet aangemaakt.  Dat moet wel.

Het doel is dat na de migratie alle servicegroepen in alle COs bestaan.  Dubbelingen zijn onwenselijk, maar minder belangrijk.

Lower prio:
- Service groep is not live updated via websocket
- auto-provisioning members settings is not disabled for service groups (maybe on purpose?)

**Comment by oharsta** [comment]
@baszoetekouw If I add a service_group to a service, then the same service on another tab shows the new service_group because of the websocket update. Or do you have a different scenario where it does not work?

@baszoetekouw As agreed, we keep the current auto-provisioning members functionality until we have the correct requirements. Ok?

**Comment by baszoetekouw** [comment]
Getest, en lijkt nu allemaal in orde

**Comment by baszoetekouw** [comment]
Fixed the names in 6b8d8b3
