### ISSUE TITLE
SCIM error

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#601]
```
Mar 22 08:47:12 sbs-pf1 python[4148]: ERROR [apscheduler.executors.default] Job "scim_sweep_services (trigger: cron[day='*', hour='*', minute='*/15'], next run at: 2023-03-22 09:00:00 UTC)" raised an exception
Mar 22 08:47:12 sbs-pf1 python[4148]: Traceback (most recent call last):
Mar 22 08:47:12 sbs-pf1 python[4148]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
Mar 22 08:47:12 sbs-pf1 python[4148]:     retval = job.func(*job.args, **job.kwargs)
Mar 22 08:47:12 sbs-pf1 python[4148]:   File "/opt/sbs/sbs/server/cron/scim_sweep_services.py", line 51, in scim_sweep_services
Mar 22 08:47:12 sbs-pf1 python[4148]:     return obtain_lock(app, scim_sweep_services_lock_name, _do_scim_sweep_services, _result_container)
Mar 22 08:47:12 sbs-pf1 python[4148]:   File "/opt/sbs/sbs/server/cron/shared.py", line 14, in obtain_lock
Mar 22 08:47:12 sbs-pf1 python[4148]:     return success(app) if lock_obtained else failure()
Mar 22 08:47:12 sbs-pf1 python[4148]:   File "/opt/sbs/sbs/server/cron/scim_sweep_services.py", line 38, in _do_scim_sweep_services
Mar 22 08:47:12 sbs-pf1 python[4148]:     sync_results = perform_sweep(service)
Mar 22 08:47:12 sbs-pf1 python[4148]:   File "/opt/sbs/sbs/server/scim/sweep.py", line 193, in perform_sweep
Mar 22 08:47:12 sbs-pf1 python[4148]:     membership_scim_objects = _memberships(group, remote_users_by_external_id)
Mar 22 08:47:12 sbs-pf1 python[4148]:   File "/opt/sbs/sbs/server/scim/sweep.py", line 109, in _memberships
Mar 22 08:47:12 sbs-pf1 python[4148]:     scim_object = remote_users_by_external_id[member.user.external_id]
Mar 22 08:47:12 sbs-pf1 python[4148]: KeyError: '3e12045a-f9a7-46d6-aeba-d3e7ae5d0459'
```

**Comment by oharsta** [comment]
@HarryKodden @baszoetekouw The error above happens during a sweep when a SRAM user which is not present in the remote SCIM server, is provisioned in the remote SCIM, but this fails. Later in the sweep when the remote groups are compared to the SRAM groups, the user is expected to be present in a dict, but is not due to the inital failure in provisioning this user.

I have implemented a fix, to be more defensive, but the underlying problem is a invalid response of the remote SCIM server. The invalid response is logged:
```
logger.error(f"Scim endpoint {service.scim_url} returned an error: {scim_json}")
```
So I would recommend searching the logs for the root cause of this error.

**Comment by baszoetekouw** [comment]
I find a zillion of these:
```
Mar 01 22:30:25 sbs-pf1 python[9156]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl/api/v4 returned an error: {}
```

That's @HarryKodden's server, I think.

**Comment by HarryKodden** [comment]
@oharsta The mechanism during SCIM updates to a Remote SCIM Server forllows this pattern:
* Lookup in Remote SCIM for existing resources
* Based on the existing resources: Apply updates (Delete/Add/Update) so that remote resources are becoming equivalent to the corresponding SBS resources.

In case of a Time-Out or Error during the Lookup, the follow up updates should not be executed. This could result in Duplicate resources in the Remote SCIM Server. Anyway the follow up requests should not be executed if the initial lookup request is unsuccessful for whatever reason.
