### ISSUE TITLE
second-factor SSO should be limited to current session

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#672]
So, if a user logs in in the same session/browser/computer within 10 minutes, the current situation (SSO is skipped) is as expected.

However, if the user logs in in another browser/session/computer within that same interval, we do need to require a second factor.

**Comment by oharsta** [comment]
In the current “/api/users/proxy_authz” flow we check if a user has a last_login_date shorter than 10 minutes. If so, we skip MFA. See https://github.com/SURFscz/SBS/blob/main/server/api/user_saml.py#L180. Issue https://github.com/SURFscz/SBS/issues/672 dictates that we only should skip MFA if there is an active session for the user. However the POST to “/api/users/proxy_authz” is a back-channel call from eduTeams to SRAM. There never will be a session, because of the lack of browser cookies. As a result the status result to eduTeams will always be `interrupt` and this is not what we want.

**Comment by baszoetekouw** [comment]
Maybe the proper way to fix this is by not checking for the SSO timeout during the `proxy_authz` call, but rather on the actual TOTP and SSID pages (so after the user has been redirected to SBS).  

So the flow would then be:
 - `proxy_authz` check if user's IdP is configured for TOTP/SSID
 - when user is redirected to TOTP or SSID pages, then check for SSO-timeout in the user's session
 - only actually ask for TOTP or send user to SSID if the user hasn't done 2FA in the past X minutes
 - continue the flow as if the user had sucessfuly entered a TOTP/completed SSID login

Would that work?

**Comment by oharsta** [comment]
This needs to be re-analysed once the branch https://github.com/SURFscz/SBS/tree/feature/refactor-login-process-883 is merged into the main branch. The solution will be much simpler as we don't support SSID anymore then.

**Comment by oharsta** [comment]
The https://github.com/SURFscz/SBS/tree/feature/refactor-login-process-883 is finished and merged. This issue can be tested.

**Comment by mrvanes** [comment]
I believe these findings align with required behaviour, but please double check:
![Image](https://github.com/user-attachments/assets/3f63b0c2-68e9-4150-ac67-5ee08a336add)

**Comment by mrvanes** [comment]
OK
