### ISSUE TITLE
Switching Service from "always allow" to "choose for each Org" leads to inconsistent state

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#778]
To reproduce:
 - set service to "Always allow connections from collaborations for all organisations" in the "Organisational access"
 - connect an Org or a CO to the Service
 - switch the Service to "Choose permission for each Org"
 
result: all Orgs are set to "Disallow" but the previously connected COs and Orgs are still connected.

desired result: Orgs that are connected or have COs that are connected should be set to "Always" by default.  Other Orgs should be set to "Disallow" by default.

**Comment by oharsta** [comment]
@baszoetekouw If you switch to "Choose permission for each organisation" then the previous state is used. No entries are deleted or added from the association table between allowed_organisations and services if you choose "Always allow connections from collaborations for all organisations" or "Manually approve connection requests from collaborations for all organisations". Because the latter two are boolean values per service.

This is by design and was also in the requirements. The advantage is that if you have many organisations and you "play" with the checkboxes then not all associations are deleted / added and you can easily restore the situation you had. Only if you explicitly Disallow connections for an organisation, then the actual CO's connected are removed (with a warning modal).

Let's discuss in person what the desired behaviour is and also take https://github.com/SURFscz/SBS/issues/867 into account.

**Comment by FlorisFokkinga** [comment]
After reconsidering, works as intended.
