### ISSUE TITLE
Web page title should be viewed object, instead of 'Research Access Management'.

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#963]
SRAM - [object name]
SRAM - [form name]
Research Access Management for pages without an object/form/profile/etc.

![Image](https://user-images.githubusercontent.com/80269262/268243232-07261802-0bae-4f08-9c2d-9799e8c00611.png)

**Comment by oharsta** [comment]
I suggest using the Breadcrumbs component to implement this generically in order to avoid having to hardcode this in every page. See https://github.com/SURFscz/SBS/blob/main/client/src/components/BreadCrumb.jsx. Exceptions to the general  rule / specific title alterations (like title 'Research Access Management' for the Home page) can be coded here

**Comment by baszoetekouw** [comment]
Works
